name: Publish package
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to NPM Registry
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@breeffy' 
    - run: yarn install --frozen-lockfile
    - run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_BREEFFY_ORG_PUBLISH_TOKEN }}
    - name: Publish to GitHub Registry
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@breeffy'
    - run: yarn install --frozen-lockfile
    - run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}